config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :executions
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'reservations/auto/daily/:date', to: 'reservations#daily', as: :auto_daily
  get 'reservations/auto/shop/:id', to: 'reservations#shop', as: :auto_shop

  root 'reservations#daily'
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reservations
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :cd)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      ul
        - @shop.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cd
    = f.text_field :cd
  .actions = f.submit

app/views/shops/edit.html.slim
h1 Editing shop

== render 'form'

= link_to 'Show', @shop
'|
= link_to 'Back', shops_path

app/views/shops/index.html.slim
h1 Listing shops

table.table
  thead
    tr
      th Name
      th Cd
      th
      th
      th

  tbody
    - @shops.each do |shop|
      tr
        td = shop.name
        td = shop.cd
        td = link_to 'Show', shop
        td = link_to 'Edit', edit_shop_path(shop)
        td = link_to 'Destroy', shop, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Shop', new_shop_path

app/views/shops/new.html.slim
h1 New shop

== render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.slim
p#notice = notice

p
  strong Name:
  = @shop.name
p
  strong Cd:
  = @shop.cd

= link_to 'Edit', edit_shop_path(@shop)
'|
= link_to 'Back', shops_path