config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :executions
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'reservations/auto/daily/:date', to: 'reservations#daily', as: :auto_daily
  get 'reservations/auto/shop/:id', to: 'reservations#shop', as: :auto_shop

  root 'reservations#daily'
end

app/models/execution.rb
class Execution < ApplicationRecord
  extend Enumerize

  enumerize :kind, in: [:auto, :manual], scope: true

  has_many :reservations, dependent: :destroy

  def manual(date = Date.today)
    self.kind = :manual
    self.execute_datetime = date

    Shop.all.each do |shop|
      (10..18).each do |hour|
        amount = reservation(shop, date, hour)
        reservations.build(shop: shop, amount: amount, scheduled_datetime: date.to_time + hour.hours)
        sleep(0.2)
      end
    end
    save
  end

  def auto(date = Date.today, time = Time.current)
    hour = time.hour
    self.kind = :auto

    Shop.all.each do |shop|
      amount = reservation(shop, date, hour)
      reservations.build(shop: shop, amount: amount,  scheduled_datetime: date.to_time + hour.hours)
      sleep(0.2)
    end
    save
  end

  def self.batch
    e = new
    date = Date.today
    e.auto(date, date.to_time + Time.current.hour.hours + 1.hours)
  end

  def self.seed
    start_date = Date.today + 1
    end_date = start_date + 4
    hours = (10..18)
    (start_date..end_date).each do |date|
      hours.each do |hour|
        e = new
        e.auto(date, date.to_time + hour.hours)
      end
    end


  end

  private

  def reservation(shop, date, hour)
    uri      = URI.parse("https://epark.jp/receive/wait/reserve_minute_select_ajax/#{shop.cd}?reserve[receipt_date][date]=#{date.to_time.to_i}&reserve[receipt_date][hour]=#{hour}")
    response = Net::HTTP.get_response(uri)

    doc = Nokogiri::HTML.parse(response.body)

    doc.xpath('//select').xpath('//option').size - 1
  end
end

app/controllers/executions_controller.rb
class ExecutionsController < ApplicationController
  before_action :set_execution, only: [:show, :edit, :update, :destroy]

  # GET /executions
  # GET /executions.json
  def index
    @executions = Execution.with_kind(:manual).order(:execute_datetime)
    @execution = Execution.new
  end

  # GET /executions/1
  # GET /executions/1.json
  def show
    @reservations = @execution.reservations.group_by{|x|x.shop.name}
  end

  # GET /executions/new
  def new
    @execution = Execution.new
  end

  # GET /executions/1/edit
  def edit
  end

  # POST /executions
  # POST /executions.json
  def create
    @execution = Execution.new

    date = Date.parse(execution_params[:execute_datetime]) rescue nil

    respond_to do |format|
      if date && @execution.manual(date)
        format.html { redirect_to @execution, notice: 'Execution was successfully created.' }
        format.json { render :show, status: :created, location: @execution }
      else
        @executions = Execution.with_kind(:manual)
        format.html { render :index }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executions/1
  # PATCH/PUT /executions/1.json
  def update
    respond_to do |format|
      if @execution.update(execution_params)
        format.html { redirect_to @execution, notice: 'Execution was successfully updated.' }
        format.json { render :show, status: :ok, location: @execution }
      else
        format.html { render :edit }
        format.json { render json: @execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executions/1
  # DELETE /executions/1.json
  def destroy
    @execution.destroy
    respond_to do |format|
      format.html { redirect_to executions_url, notice: 'Execution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_execution
      @execution = Execution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def execution_params
      params.require(:execution).permit(:execute_datetime, :kind)
    end
end

app/helpers/executions_helper.rb
module ExecutionsHelper
end

app/views/executions/_form.html.slim
= form_for @execution do |f|
  - if @execution.errors.any?
    #error_explanation
      h2 = "#{pluralize(@execution.errors.count, "error")} prohibited this execution from being saved:"
      ul
        - @execution.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :execute_datetime
    = f.datetime_select :execute_datetime
  .field
    = f.label :kind
    = f.text_field :kind
  .actions = f.submit

app/views/executions/edit.html.slim
h1 Editing execution

== render 'form'

= link_to 'Show', @execution
'|
= link_to 'Back', executions_path

app/views/executions/index.html.slim
h1 特定の日の予約状況

= form_for @execution do |f|
  = f.text_field :execute_datetime
  = f.submit '取得する', class: 'submit-button'

table.table
  thead
    tr
      th 取得日
      th 予約日
      th
      th

  tbody
    - @executions.each do |execution|
      tr
        td = l execution.created_at
        td = l execution.execute_datetime.to_date
        td = link_to 'Show', execution, class: 'show-button'
        td = link_to 'Destroy', execution, data: { confirm: 'Are you sure?' }, method: :delete, class: 'destroy-button'

app/views/executions/new.html.slim
h1 New execution

== render 'form'

= link_to 'Back', executions_path

app/views/executions/show.html.slim
h1 = "#{l@execution.created_at}に取得した#{l @execution.execute_datetime.to_date}の予約状況"

table.table
  tr
    th
    -(10..18).each do |hour|
      th = hour

  - @reservations.each do |shop_name, reservations|
    tr
      th = shop_name
      -(10..18).each do |hour|
        - r = reservations.find {|r| r.scheduled_datetime.hour == hour}
        td = r&.amount


= link_to 'Back', executions_path, class: 'back-button'