config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  resources :executions
  resources :shops
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'reservations/auto/daily/:date', to: 'reservations#daily', as: :auto_daily
  get 'reservations/auto/shop/:id', to: 'reservations#shop', as: :auto_shop

  root 'reservations#daily'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :shop
  belongs_to :execution
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def daily
    @date = Date.parse(params[:date]) rescue Date.today
    @reservations = Reservation.joins(:execution).where(executions: { kind: :auto }).where(scheduled_datetime: (@date.beginning_of_day..@date.end_of_day)).order(:scheduled_datetime)
  end

  def shop
    @shop = Shop.find(params[:id])
    @reservations = Reservation.joins(:execution).where(executions: { kind: :auto }).where(shop_id: @shop.id).order(:scheduled_datetime).group_by{|x| x.scheduled_datetime.to_date }
  end

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:shop_id, :execution_id, :amount, :scheduled_datetime)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.slim
= form_for @reservation do |f|
  - if @reservation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@reservation.errors.count, "error")} prohibited this reservation from being saved:"
      ul
        - @reservation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :shop
    = f.text_field :shop
  .field
    = f.label :execution
    = f.text_field :execution
  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :scheduled_datetime
    = f.datetime_select :scheduled_datetime
  .actions = f.submit

app/views/reservations/daily.html.slim
h1 = "#{l @date}の予約履歴"
= link_to "<< #{@date - 1}", auto_daily_path(date: @date - 1)
= link_to " #{@date + 1} >>", auto_daily_path(date: @date + 1)
table.table
  tr
    th
    - (10..18).each do |hour|
      th = hour
  - Shop.all.each do |shop|
    tr
      th = link_to shop.name, auto_shop_url(shop.id)
      - (10..18).each do |hour|
        - r = @reservations.find { |r| r.shop_id == shop.id && r.scheduled_datetime == (@date + hour.hours) }
        td = r&.amount

app/views/reservations/edit.html.slim
h1 Editing reservation

== render 'form'

= link_to 'Show', @reservation
'|
= link_to 'Back', reservations_path

app/views/reservations/index.html.slim
h1 Listing reservations

table
  thead
    tr
      th Shop
      th Execution
      th Amount
      th Scheduled datetime
      th
      th
      th

  tbody
    - @reservations.each do |reservation|
      tr
        td = reservation.shop
        td = reservation.execution
        td = reservation.amount
        td = reservation.scheduled_datetime
        td = link_to 'Show', reservation
        td = link_to 'Edit', edit_reservation_path(reservation)
        td = link_to 'Destroy', reservation, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Reservation', new_reservation_path

app/views/reservations/new.html.slim
h1 New reservation

== render 'form'

= link_to 'Back', reservations_path

app/views/reservations/shop.html.slim
h1 = "#{@shop.name}の予約履歴"

- Shop.all.each do |shop|
  = link_to shop.name, auto_shop_url(id: shop.id)
  |  /
table.table
  tr
    th
    - (10..18).each do |hour|
      th = hour
    - @reservations.each do |date, reservations|
      tr
        th = link_to date, auto_daily_path(date: date)
        - (10..18).each do |hour|
          - r = reservations.find { |r| r.scheduled_datetime == (date + hour.hours) }
          td = r&.amount

app/views/reservations/show.html.slim
p#notice = notice

p
  strong Shop:
  = @reservation.shop
p
  strong Execution:
  = @reservation.execution
p
  strong Amount:
  = @reservation.amount
p
  strong Scheduled datetime:
  = @reservation.scheduled_datetime

= link_to 'Edit', edit_reservation_path(@reservation)
'|
= link_to 'Back', reservations_path